- .travis.yml
This PR will Update travis file
- update dockerhub Organization to litmuschaos
Signed-off-by: inyee786 <intakhab.ali@mayadata.io>
> Update travis file with litmus dockerhub Organization

- .travis.yml
Signed-off-by: inyee786 <intakhab.ali@mayadata.io>
> Update travis file with litmus dockerhub Organization (#59)

- src/app/components/banner/banner.component.html
- src/app/components/banner/banner.component.ts
- src/app/shared/header/header.component.html
Signed-off-by: isamrish <askmaurya48@gmail.com>
> Remove banner

- src/app/components/banner/banner.component.html
- src/app/components/banner/banner.component.ts
- src/app/shared/header/header.component.html
Signed-off-by: isamrish <askmaurya48@gmail.com>
- Remove banner (#63)
> [Staging to Master]

- src/app/pages/home/home.component.html
Example link has been updated to docs
Signed-off-by: ajeshbaby <ajesh.baby@mayadata.io>
> Update example link

- src/app/pages/home/home.component.html
Signed-off-by: ajeshbaby <ajesh.baby@mayadata.io>
> Update example link (#65)

- README.md
- Add license scan badge in README
Signed-off-by: ksatchit <ksatchit@mayadata.io>
> (chore)license: add license badge

- src/app/pages/home/home.component.css
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.ts
Signed-off-by: arkajyotiMukherjee <arkajyoti31@gmail.com>
> changed Icon size and Comminuty button name to slack

- src/index.html
Signed-off-by: isamrish <askmaurya48@gmail.com>
This commit will update tracking code of google analytics for
https://litmuschaos.io
Updated tracking code is `UA-92076314-26`.
> Update GA code

- src/index.html
Signed-off-by: isamrish <askmaurya48@gmail.com>
This commit will update tracking code of google analytics for
https://litmuschaos.io
Updated tracking code is `UA-92076314-26`.
> [Staging to Production]

- src/app/pages/home/home.component.html
The actual change is just one line, but my code formatted kicked in and beautified the page.
Signed-off-by: arkajyotiMukherjee <arkajyoti.mukherjee@mayadata.io>
> added link to the mayadata logo to website

- src/app/pages/home/home.component.ts
- src/app/shared/footer/footer.component.html
- src/app/shared/footer/footer.component.ts
- src/app/shared/header/header.component.html
Add litmuschaos/litmus to the github links on website main page
Signed-off-by: Uma Mukkara <uma@mayadata.io>
> Cherry pick from staging to master

- src/app/pages/home/home.component.html
- Update the link to litmus manifests on website 
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> (chore)manifests: update litmus manifests version

- src/app/pages/home/home.component.html
Signed-off-by: ksatchit <karthik.s@mayadata.io>
**Cherry-picked commits:**
- (chore)manifests: update litmus manifests version (#81)
> [Prod]: Cherry-pick changes from staging

- gatsby-config.js
- nginx-custom.conf
- package.json
- src/components/footer/Footer.tsx
- src/components/layout/Sections.tsx
- src/components/nav/Nav.tsx
- src/components/sections/chaoshub/ReadyToStart.tsx
- src/components/sections/home/CloudNativeWay.tsx
- src/components/sections/home/GetStarted.tsx
- src/components/sections/home/QuickStart.tsx
- src/components/sections/whylitmus/Features.tsx
- src/components/terminal/Terminal.tsx
- src/pages/chaoshub.tsx
- src/styles/theme.tsx
Various fixes made, added google analytics and google tag manager to the website; bounded the website for larger screens...fixed typos
> Google analytics added

- gatsby-config.js
- src/components/info-section/StatCard.tsx
- src/components/sections/chaoshub/ChaoshubStatistics.tsx
- src/components/texts/Texts.tsx
- src/models/analytics.ts
Signed-off-by: arkajyotiMukherjee <arkajyoti.mukherjee@mayadata.io>
> changed google analytics settings and added stats for chaoshub page

- gatsby-config.js
- src/components/info-section/StatCard.tsx
- src/components/sections/chaoshub/ChaoshubStatistics.tsx
- src/components/texts/Texts.tsx
- src/models/analytics.ts
changed google analytics settings and added stats for chaoshub page
> Cherry pick for stats and google analytics

- src/components/footer/Footer.tsx
Added Linux Trademark Usage Link to Footer
> Added Linux Trademark Usage Link to Footer (#99)

- .gitignore
- gatsby-config.js
- public/page-data/chaoshub/page-data.json
- public/page-data/community/page-data.json
- public/page-data/index/page-data.json
- public/page-data/whylitmus/page-data.json
- src/components/pre-footer/data.ts
- src/components/sections/community/CommunityEvents.tsx
- src/components/seo/SEO.tsx
Signed-off-by: Sayan Mondal <sayan.mondal@mayadata.io>
Social Media Card link added to SEO directly since Site Manifest is storing cache and not deleting previously stored siteImage.png
Adding image link directly to SEO component header and sharing it globally using React Helmet.
> Updated CNCF Meetup URL + Updated Social Media Card

- src/components/nav/Burger.tsx
Cherry-pick: ae0158c
* Changed open-handling logic; Repositioned div to inside hamburger menu; <StyledBurger> now position: relative; <BurgerModal> now position absolute; Removed margin from <BurgerModal>
* Added cursor: pointer to menu
Co-authored-by: Arkajyoti Mukherjee <32966391+arkajyotiMukherjee@users.noreply.github.com>
> chery-pick: Addressing issue #120 (#123)

- src/components/sections/community/LitmusCommunityVideo.tsx
- src/components/sections/home/QuickStart.tsx
Signed-off-by: Sayan Mondal <sayan.mondal@mayadata.io>
> Updated Litmuschaos QuickStart + Community videos

- src/components/sections/community/LitmusCommunityVideo.tsx
- src/components/sections/home/QuickStart.tsx
Cherry Picking 94fc437ab90c21254650937ce737b3cd98e5be95
Updated Videos and recent LitmusChaos Items
> Cherry pick 94fc437

- src/components/sections/home/GetStarted.tsx
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> (fix)install: update the install steps

- src/components/sections/home/GetStarted.tsx
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> Cherry pick manifest fix [70acaa681640be88fcf344adc320fa31a1c8e90a]

- src/pages/404.tsx
Signed-off-by: SarthakJain26 <sarthak.jain@mayadata.io>
- Added Link to `Go back home` button in /404/ route
> Added Link to Go "Go back home" button

- src/components/nav/Burger.tsx
- src/components/pre-footer/PreFooterMid.tsx
Signed-off-by: Hrishav Kumar <hrishav@chaosnative.com>
> Fixed text appearing twice & updated mobile navbar links

- src/components/nav/Burger.tsx
- src/components/pre-footer/PreFooterMid.tsx
- Fixed repeating texts
- Updated mobile nav links
Signed-off-by: Hrishav Kumar <hrishav@chaosnative.com>
Signed-off-by: Sahil <sahil@chaosnative.com>
> Fixed Issues & updated mobile nav links (#162)

- gatsby-config.js
- package-lock.json
- package.json
Signed-off-by: Sahil <sahil@chaosnative.com>
> updated sitemap path to /

- gatsby-config.js
- package-lock.json
- package.json
Signed-off-by: Sahil <sahil@chaosnative.com>
> updated sitemap path to / (#170)

- src/components/sections/community/LitmusCommunityVideo.tsx
- src/components/sections/home/QuickStart.tsx
- yarn.lock
Signed-off-by: Hrishav Kumar <hrishav@chaosnative.com>
> Updated community video

- src/components/sections/community/LitmusCommunityVideo.tsx
- src/components/sections/home/QuickStart.tsx
- yarn.lock
Signed-off-by: Hrishav Kumar <hrishav@chaosnative.com>
> Updated community and tutorial video (#172)
